= Welcome to Red Hat Solutions Patterns for Cloud Native Applications
:page-layout: home
:!sectids:

[.text-center.strong]
[#intro]
== Cloud native architectures done right

Learn about common scenarios faced by developers and architects, its challenges and proposed architectural solutions with Red Hat technologies. Here you can find solution for diverse set of use cases on cloud adoption and application modernization, including background story, reference architecture, technical implementation of the solution and much more.

[#whatis]
== What is a solution pattern?

The Red Hat cloud native architecture (CNA) solution patterns are a set of opinionated practices on how to design, develop, integrate, automate and deliver cloud native applications. It targets common problems and use cases faced by organizations that target digital transformation through cloud adoption and who are on the journey of app modernization. 
  
Each solution pattern documents a specific reference architecture that can be replicated or can be used to inspire technical decision makers on how to achieve their goals. 

All the solutions are built on top of the Red Hat technologies portfolio, combined with other complementing open source technologies, to showcase how Red Hat provides the ultimate cloud-native application platform so that you can spend less time dealing with operational tasks and more time building applications.



[#explore]
== Explore Red Hat Solution Patterns

View the list of xref::patterns.adoc[Solution Patterns]

Go ahead and _drive innovation_ and _boost productivity_ with the solution patterns.
