

== The Solution Patterns
:page-layout: home
:!sectids:
It's time to boost your cloud-native application architectural design with bleeding-edge technology backed by open-source software. Explore the use cases and learn recommended solutions for each of these challenges.



++++

<div class="container">
 
 
<a href="https://redhat-solution-patterns.github.io/solution-pattern-modernization-cdc" target="_blank" class="col card">
    
    <div><strong>Modernize your stack by adopting Change Data Capture</strong></div>
    <div style="font-size:14px">Extend capabilities with no changes to legacy apps through data integration and cause no impact to the existing stack</div>
</a>

 
<a href="https://redhat-solution-patterns.github.io/rh-solution-patterns/redhat-solution-patterns.github.io/solution-pattern-enhancing-applications" target="_blank"  class="col card">  
    <div><strong>Enhancing Applications with Application Services</strong></div>
    <div style="font-size:14px">
      Enhance apps with cloud native streaming and API management
    </div>
</a>

 
<a href="https://redhat-solution-patterns.github.io/solution-pattern-sentiment-analysis" target="_blank"  class="col card">
    <div><strong>Sentiment Analysis with Kafka + AIML throught Knative Event Driven Architecture</strong></div>
    <div style="font-size:14px">
      Event driven scalable and efficient system capturing and responding to streaming data using Kafka as the streaming platform and AIML.
    </div>
</a>

 
<a href="https://redhat-solution-patterns.github.io/solution-pattern-apim-servicemesh" target="_blank"  class="col card">  
    <div><strong>Comprehensive Service Architecture with API Management and Service Mesh</strong></div>
    <div style="font-size:14px">
      use API management and service mesh together to setup a comprehensive service management architecture
    </div>
</a>

<a href="https://redhat-solution-patterns.github.io/solution-pattern-multicloud-gitops-odf" target="_blank"  class="col card">  
    <div><strong>MultiCloud GitOps with ODF</strong></div>
    <div style="font-size:14px">
      Demonstrate how ArgoCD with Red Hat ACM can manage different clusters and applications deployed on those clusters
    </div>
</a>

<a href="https://redhat-solution-patterns.github.io/solution-pattern-modernize-with-rosa" target="_blank"  class="col card">  
    <div><strong>Accelerate time to value with Red Hat Openshift Service on AWS</strong></div>
    <div style="font-size:14px">
      Demonstrate the integration of Red Hat Openshift Service on AWS(ROSA) with different AWS services
    </div>
</a>



</div>
++++


